// ─── Story & Content Types ───────────────────────────────────────────────────

export type StoryGroupStatus = 'active' | 'inactive' | 'test' | 'archived' | 'scheduled';

export type StoryStatus = 'active' | 'archived';

export type StoryType = 'image' | 'video';

export type AudienceType = 'none' | 'labels' | 'custom';

export type InteractiveComponentType = 'poll' | 'quiz' | 'cta' | 'emoji' | 'countdown' | 'swipe';

export interface InteractiveComponent {
  id: string;
  type: InteractiveComponentType;
  config: Record<string, unknown>;
}

export interface Story {
  id: string;
  title: string;
  thumbnail: string;
  videoUrl?: string;
  /** Tailwind gradient classes for template-based stories (e.g. "from-rose-500 to-orange-400") */
  gradient?: string;
  /** ID referencing a template component from the template registry */
  templateId?: string;
  status: StoryStatus;
  type: StoryType;
  interactiveComponents: InteractiveComponent[];
  /** Whether this story was generated by the AI generator */
  aiGenerated?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Widget {
  id: string;
  name: string;
  platform: 'ios' | 'android' | 'web';
  appName: string;
  appIcon: string;
  token: string;
  createdAt: string;
}

export interface StoryGroup {
  id: string;
  title: string;
  coverImage: string;
  status: StoryGroupStatus;
  storiesCount: number;
  stories: Story[];
  audience: AudienceType;
  labels: string[];
  widgetIds: string[];
  schedule: {
    start: string | null;
    end: string | null;
  };
  isPinned: boolean;
  isSponsored: boolean;
  createdAt: string;
  updatedAt: string;
}

// ─── Analytics Types ─────────────────────────────────────────────────────────

export interface AnalyticsData {
  storyGroupId: string;
  reach: number;
  impressions: number;
  clicks: number;
  ctr: number;
  completionRate: number;
  activeUsers: number;
  tapForward: number;
  tapBackward: number;
  avgWatchLength: number;
  shareFromClick: number;
}

export interface KPIMetric {
  id: string;
  label: string;
  value: number;
  previousValue: number;
  trend: 'up' | 'down' | 'flat';
  format: 'number' | 'percentage' | 'currency';
  description: string;
}

export interface ChartDataPoint {
  date: string;
  reach: number;
  impressions: number;
  clicks: number;
  activeUsers: number;
  eventTracker: number;
}

export type ChartMetric = 'reach' | 'impressions' | 'clicks' | 'activeUsers' | 'eventTracker';

export type ChartInterval = 'daily' | 'weekly' | 'monthly';

// ─── Activity Types ──────────────────────────────────────────────────────────

export type ActivityAction =
  | 'created'
  | 'updated'
  | 'published'
  | 'archived'
  | 'duplicated'
  | 'deleted'
  | 'scheduled';

export interface ActivityItem {
  id: string;
  action: ActivityAction;
  targetType: 'story_group' | 'story' | 'widget';
  targetName: string;
  userId: string;
  userName: string;
  userAvatar: string;
  timestamp: string;
}

// ─── Team & User Types ──────────────────────────────────────────────────────

export type UserRole = 'owner' | 'admin' | 'editor' | 'viewer';

export interface TeamMember {
  id: string;
  name: string;
  email: string;
  avatar: string;
  role: UserRole;
  lastActive: string;
  joinedAt: string;
}

// ─── Billing Types ──────────────────────────────────────────────────────────

export type PlanTier = 'free' | 'starter' | 'growth' | 'enterprise';

export type InvoiceStatus = 'paid' | 'pending' | 'overdue' | 'failed';

export interface BillingPlan {
  id: string;
  name: string;
  tier: PlanTier;
  price: number;
  currency: string;
  interval: 'monthly' | 'yearly';
  features: string[];
  limits: {
    storyGroups: number;
    storiesPerGroup: number;
    widgets: number;
    teamMembers: number;
    monthlyImpressions: number;
  };
}

export interface PaymentMethod {
  id: string;
  type: 'card' | 'bank';
  brand: string;
  last4: string;
  expiryMonth: number;
  expiryYear: number;
  isDefault: boolean;
}

export interface Invoice {
  id: string;
  number: string;
  amount: number;
  currency: string;
  status: InvoiceStatus;
  issuedAt: string;
  dueAt: string;
  paidAt: string | null;
  downloadUrl: string;
}

// ─── Navigation Types ───────────────────────────────────────────────────────

export interface NavItem {
  title: string;
  href: string;
  icon: string;
  badge?: string | number;
  children?: NavItem[];
}

export interface BreadcrumbItem {
  label: string;
  href?: string;
}
